#yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: Order Service and API docs
site_url: https://bfium.github.io/order-service-docs/
theme:
  name: material
  features:
    - navigation.indexes
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - search
  - blog:
      blog_toc: true
      archive_date_format: MMM yyyy
      categories_allowed:
        - it
        - News
      authors_profiles: true
      pagination_per_page: 5
      categories_pagination_per_page: 6
  - tags
  - rss:
      match_path: "blog/posts/."
      date_from_meta:
        as_creation: date.created
        as_update: date.updated


links:
  - index.md
  - blog/index.md

nav:
  - Home: index.md
  - Install: install.md
  - Usage: usage.md
  - Blog:
      - blog/index.md