site_name: Order Service and API Docs
site_url: https://bfium.github.io/order-service-docs/
theme:
  name: material
  custom_dir: overrides
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.instant.progress
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - navigation.top
    #- navigation.sections
    - toc.follow
    #- toc.integrate

  font:
    text: times

  logo: assets/logo.png
  icon:
    #previous: fontawsome/solid/angle-left
    next: fontawsome/solid/angle-right




  palette:
      - media: "(prefers-color-scheme: light)"
        scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
          # Palette toggle for dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

plugins:
  - privacy
  - social: # lern more here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/
      cards_layout_options:
        font_family: Time
  - search
  #- search.suggest
  #- search.highlight
  #- search.share

  - blog: # learn more : https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
      blog_toc: true
      archive_date_format: MMM yyyy
      authors_profiles: true
      categories_allowed:
        - IT
        - News
      pagination_per_page: 5
  - tags
  - rss:  # learn more here: https://squidfunk.github.io/mkdocs-material/setup/setting-up-a-blog/
      match_path: "blog/posts/."
      date_from_meta:
        as_creation: date.created
        as_update: date.updated
      categories:
        - categories
        - tags
      comments_path: "#__comments"

extra:
  social:
    - icon: fontawesome/brands/linkedin
      name: Barth Feudong
      link: https://www.linkedin.com/in/barth-feudong/
    - icon: fontawesome/regular/envelope
      name: Send me an email
      link: mailto:<email-address>
    - icon: material/mailbox
      name: Contact us
      link: /contact

  content:
    title: Cookie consent
    description: >- 
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.
    actions:
      - accept
      - manage
      - reject
copyright: >
  Copyright &copy; 2016 - 2024 Barth. Feudong –
  <a href="#__consent">Change cookie settings</a>

nav:
  - Home: index.md
  - Introduction: introduction.md
  - Architecture: architecture.md
  - Blog:
      - blog/index.md
      - blog/author/barth_feudong.md

